  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  cart_arm1_joint0_controller:
    type: effort_controllers/JointPositionController
    joint: C_A1_L0
    pid: {p: 2000.0, i: 0.01, d: 10.0}

  cart_arm1_joint1_controller:
    type: effort_controllers/JointPositionController
    joint: C_A1_L1
    pid: {p: 100.0, i: 30, d: 10.0}

  cart_arm1_joint2_controller:
    type: effort_controllers/JointPositionController
    joint: C_A1_L2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm1_joint3_controller:
    type: effort_controllers/JointPositionController
    joint: C_A1_L3
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm1_joint4_controller:
    type: effort_controllers/JointPositionController
    joint: C_A1_L4
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm2_joint0_controller:
    type: effort_controllers/JointPositionController
    joint: C_A2_L0
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm2_joint1_controller:
    type: effort_controllers/JointPositionController
    joint: C_A2_L1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm2_joint2_controller:
    type: effort_controllers/JointPositionController
    joint: C_A2_L2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm2_joint3_controller:
    type: effort_controllers/JointPositionController
    joint: C_A2_L3
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm3_joint0_controller:
    type: effort_controllers/JointPositionController
    joint: C_A3_L0
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm3_joint1_controller:
    type: effort_controllers/JointPositionController
    joint: C_A3_L1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm3_joint2_controller:
    type: effort_controllers/JointPositionController
    joint: C_A3_L2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm3_joint3_controller:
    type: effort_controllers/JointPositionController
    joint: C_A3_L3
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm3_joint4_controller:
    type: effort_controllers/JointPositionController
    joint: C_A3_L4
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm4_joint0_controller:
    type: effort_controllers/JointPositionController
    joint: C_A4_L0
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm4_joint1_controller:
    type: effort_controllers/JointPositionController
    joint: C_A4_L1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm4_joint2_controller:
    type: effort_controllers/JointPositionController
    joint: C_A4_L2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm4_joint3_controller:
    type: effort_controllers/JointPositionController
    joint: C_A4_L3
    pid: {p: 100.0, i: 0.01, d: 10.0}

  cart_arm4_joint4_controller:
    type: effort_controllers/JointPositionController
    joint: C_A4_L4
    pid: {p: 100.0, i: 0.01, d: 10.0}
