Cart:
  C_A1_L0_controller:
    p: 2000
    i: 0
    d: 10

  C_A1_L1_controller:
    p: 2000
    i: 0
    d: 10

  C_A1_L2_controller:
    p: 2000
    i: 0
    d: 10

  C_A1_L3_controller:
    p: 2000
    i: 0
    d: 10

  C_A1_L4_controller:
    p: 2000
    i: 0
    d: 10

  C_A2_L0_controller:
    p: 2000
    i: 0
    d: 10

  C_A2_L1_controller:
    p: 2000
    i: 0
    d: 10

  C_A2_L2_controller:
    p: 2000
    i: 0
    d: 10

  C_A2_L3_controller:
    p: 2000
    i: 0
    d: 10

  C_A3_L0_controller:
    p: 2000
    i: 0
    d: 10

  C_A3_L1_controller:
    p: 2000
    i: 0
    d: 10

  C_A1_L2_controller:
    p: 2000
    i: 0
    d: 10

  C_A3_L3_controller:
    p: 2000
    i: 0
    d: 10

  C_A3_L4_controller:
    p: 2000
    i: 0
    d: 10

  C_A4_L0_controller:
    p: 2000
    i: 0
    d: 10

  C_A4_L1_controller:
    p: 2000
    i: 0
    d: 10

  C_A4_L2_controller:
    p: 2000
    i: 0
    d: 10

  C_A4_L3_controller:
    p: 2000
    i: 0
    d: 10

  C_A4_L4_controller:
    p: 2000
    i: 0
    d: 10
PSM1:
  one_outer_yaw_controller:
    p: 20
    i: 0
    d: 10
  one_outer_pitch_joint_1_controller:
    p: 600
    i: 0
    d: 0
ecm:
  outer_pitch_1_controller:
    p: 500
    i: 0
    d: 0
